export type IconType =
    | "folder"
    | "favorite"
    | "archive"
    | "daymode"
    | "nightmode"
    | "search"
    | "send"
    | "regenerate"
    | "download"
    | "like"
    | "dislike"
    | "edit"
    | "create"